function out1 = BMWrapArm_WORKING_compiled_lengths(in1,in2,in3,in4)
%BMWrapArm_WORKING_compiled_lengths
%    OUT1 = BMWrapArm_WORKING_compiled_lengths(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*t4.*2.195e-1;
t9 = t2.*t4.*2.545e-1;
t10 = t4.*t5.*2.195e-1;
t11 = t3.*t7.*2.195e-1;
t12 = t4.*t5.*2.545e-1;
t13 = t3.*t7.*2.545e-1;
t16 = t5.*t6.*t7.*2.195e-1;
t17 = t5.*t6.*t7.*2.545e-1;
t18 = t2.*t6.*t7.*2.195e-1;
t19 = t2.*t6.*t7.*2.545e-1;
t20 = t3.*t4.*2.48764e-2;
t21 = t2.*t7.*2.48764e-2;
t22 = t3.*t4.*2.5124e-2;
t23 = t5.*t7.*2.48764e-2;
t24 = t2.*t7.*2.5124e-2;
t25 = t5.*t7.*2.5124e-2;
t26 = t6.*1.8743851e-4;
t29 = t2.*t4.*t6.*2.48764e-2;
t30 = t4.*t5.*t6.*2.48764e-2;
t31 = t2.*t4.*t6.*2.5124e-2;
t32 = t4.*t5.*t6.*2.5124e-2;
t33 = t2.*t3.*1.8743851e-4;
t34 = t3.*t5.*1.8743851e-4;
t14 = -t11;
t15 = -t13;
t27 = -t20;
t28 = -t23;
t35 = -t31;
t36 = -t34;
mt1 = [sqrt((t10+t18+t28+t29+t33+1.06066e-1).^2+(t14+t26+t27+1.06066e-1).^2+(-t8+t16+t21+t30+t34+2.1e+1./1.0e+3).^2)];
mt2 = [sqrt((t12+t19+t28+t29+t33-1.06066e-1).^2+(t15+t26+t27+1.06066e-1).^2+(-t9+t17+t21+t30+t34+2.1e+1./1.0e+3).^2)];
mt3 = [sqrt((t10+t18+t25+t33+t35+1.06066e-1).^2+(t14+t22+t26-1.06066e-1).^2+(t8-t16+t24+t32+t36-2.1e+1./1.0e+3).^2)];
mt4 = [sqrt((t12+t19+t25+t33+t35-1.06066e-1).^2+(t15+t22+t26-1.06066e-1).^2+(t9-t17+t24+t32+t36-2.1e+1./1.0e+3).^2)];
out1 = [mt1;mt2;mt3;mt4];
end
