function out1 = BMWrapArm_WORKING_compiled_r_OAs(in1,in2,in3,in4)
%BMWrapArm_WORKING_compiled_r_OAs
%    OUT1 = BMWrapArm_WORKING_compiled_r_OAs(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*t4.*2.195e-1;
t9 = t2.*t4.*2.545e-1;
t10 = t4.*t5.*2.195e-1;
t11 = t3.*t7.*2.195e-1;
t12 = t4.*t5.*2.545e-1;
t13 = t3.*t7.*2.545e-1;
t16 = t5.*t6.*t7.*2.195e-1;
t17 = t5.*t6.*t7.*2.545e-1;
t18 = t2.*t6.*t7.*2.195e-1;
t19 = t2.*t6.*t7.*2.545e-1;
t22 = t3.*t4.*2.48764e-2;
t23 = t2.*t7.*2.48764e-2;
t24 = t3.*t4.*2.5124e-2;
t25 = t5.*t7.*2.48764e-2;
t26 = t2.*t7.*2.5124e-2;
t27 = t5.*t7.*2.5124e-2;
t28 = t6.*1.8743851e-4;
t32 = t2.*t4.*t6.*2.48764e-2;
t33 = t4.*t5.*t6.*2.48764e-2;
t34 = t2.*t4.*t6.*2.5124e-2;
t35 = t4.*t5.*t6.*2.5124e-2;
t36 = t2.*t3.*1.8743851e-4;
t37 = t3.*t5.*1.8743851e-4;
t14 = -t11;
t15 = -t13;
t20 = -t16;
t21 = -t17;
t29 = -t22;
t30 = -t23;
t31 = -t25;
t38 = -t33;
t39 = -t34;
t40 = -t37;
mt1 = [-1.06066e-1,2.1e+1./1.0e+3,-1.06066e-1,t14+t28+t29,t8+t20+t30+t38+t40,t10+t18+t31+t32+t36,-1.06066e-1,2.1e+1./1.0e+3,1.06066e-1,t15+t28+t29,t9+t21+t30+t38+t40,t12+t19+t31+t32+t36];
mt2 = [1.06066e-1,2.1e+1./1.0e+3,-1.06066e-1,t14+t24+t28,t8+t20+t26+t35+t40,t10+t18+t27+t36+t39,1.06066e-1,2.1e+1./1.0e+3,1.06066e-1,t15+t24+t28,t9+t21+t26+t35+t40,t12+t19+t27+t36+t39];
out1 = reshape([mt1,mt2],6,4);
end
