function out1 = BMWrapArm_ee_pose_compiled_J_dot(in1,in2,in3,in4)
%BMWrapArm_ee_pose_compiled_J_dot
%    OUT1 = BMWrapArm_ee_pose_compiled_J_dot(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q_d1 = in2(1,:);
q_d2 = in2(2,:);
q_d3 = in2(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t3.^2;
t9 = q_d2.*t4;
t10 = q_d1.*t6;
t12 = q_d1.*t3.*t7;
t11 = q_d3+t10;
t13 = -t12;
t14 = t9+t13;
mt1 = [t9.*(6.7e+1./2.5e+2)+q_d3.*t7.*sin(q2.*2.0).*(6.7e+1./5.0e+2),q_d1.*t2.*t4.*(-6.7e+1./2.5e+2)+q_d3.*t5.*t7.*(6.7e+1./2.5e+2)+t5.*t7.*t10.*(6.7e+1./2.5e+2)-q_d3.*t2.*t4.*t6.*(6.7e+1./2.5e+2)-q_d3.*t5.*t7.*t8.*(6.7e+1./2.5e+2),q_d1.*t4.*t5.*(-6.7e+1./2.5e+2)-q_d3.*t2.*t7.*(6.7e+1./2.5e+2)-t2.*t7.*t10.*(6.7e+1./2.5e+2)-q_d3.*t4.*t5.*t6.*(6.7e+1./2.5e+2)+q_d3.*t2.*t7.*t8.*(6.7e+1./2.5e+2),q_d1.*t4.*(-6.7e+1./2.5e+2)+q_d2.*t3.*t7.*(6.7e+1./2.5e+2),t7.*(q_d1.*t2.*t3.*2.0-q_d2.*t5.*t6).*(-6.7e+1./2.5e+2)];
mt2 = [t7.*(q_d1.*t3.*t5.*2.0+q_d2.*t2.*t6).*(-6.7e+1./2.5e+2),t6.*t14.*(6.7e+1./1.25e+2)+t3.*t7.*t11.*(6.7e+1./2.5e+2),t11.*(t2.*t4-t5.*t6.*t7).*(-6.7e+1./2.5e+2)-t3.*t5.*t14.*(6.7e+1./1.25e+2),t11.*(t4.*t5+t2.*t6.*t7).*(-6.7e+1./2.5e+2)+t2.*t3.*t14.*(6.7e+1./1.25e+2)];
out1 = reshape([mt1,mt2],3,3);
end
