function out1 = BMWrapArm_ee_pose_compiled_J(in1,in2,in3,in4)
%BMWrapArm_ee_pose_compiled_J
%    OUT1 = BMWrapArm_ee_pose_compiled_J(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t3.^2;
t9 = t2.*t7.*(6.7e+1./2.5e+2);
t10 = t5.*t7.*(6.7e+1./2.5e+2);
t11 = t2.*t4.*t6.*(6.7e+1./2.5e+2);
t12 = t4.*t5.*t6.*(6.7e+1./2.5e+2);
out1 = reshape([0.0,-t6.*(t9+t12)-t4.*t5.*t8.*(6.7e+1./2.5e+2),-t6.*(t10-t11)+t2.*t4.*t8.*(6.7e+1./2.5e+2),t6.*t7.*(6.7e+1./2.5e+2),t3.*t5.*t7.*(-6.7e+1./2.5e+2),t3.*t9,t3.*t4.*(-6.7e+1./2.5e+2),-t9-t12,-t10+t11],[3,3]);
end
