function P_temp = BMWrapArm_compiled_P_1_1(in1,in2,in3,in4)
%BMWrapArm_compiled_P_1_1
%    P_temp = BMWrapArm_compiled_P_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
P_temp = reshape([t3.*t4,-t3.*t7,t6,0.0,0.0,0.0,t2.*t7+t4.*t5.*t6,t2.*t4-t5.*t6.*t7,-t3.*t5,0.0,0.0,0.0,t5.*t7-t2.*t4.*t6,t4.*t5+t2.*t6.*t7,t2.*t3,0.0,0.0,0.0,0.0,0.0,1.466e-1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.466e-1,0.0,0.0,0.0,0.0,1.0],[6,6]);
end
