function out1 = BMWrapArm_compiled_M_b(in1,in2,in3,in4)
%BMWrapArm_compiled_M_b
%    OUT1 = BMWrapArm_compiled_M_b(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
mt1 = [t4.*(-1.466e-1),0.0,t2.*t3.*1.466e-1,t2.*t3.*9.740714285714001e-1,t2.*t5.*(-1.195714285714e-1),t4.*9.740714285714001e-1,0.0,0.0,t5.*1.466e-1,t5.*9.740714285714001e-1];
mt2 = [t3.*1.195714285714e-1,0.0,-1.466e-1,0.0,0.0,0.0,0.0,9.740714285714001e-1];
out1 = reshape([mt1,mt2],6,3);
end
