function out1 = BMWrapArm_compiled_S_dot(in1,in2,in3,in4)
%BMWrapArm_compiled_S_dot
%    OUT1 = BMWrapArm_compiled_S_dot(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:05

q2 = in1(2,:);
q3 = in1(3,:);
q_d2 = in2(2,:);
q_d3 = in2(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
out1 = reshape([0.0,0.0,0.0,-q_d2.*t3.*t4-q_d3.*t2.*t5,-q_d3.*t2.*t3+q_d2.*t4.*t5,q_d2.*t2,0.0,0.0,0.0,q_d3.*t3,-q_d3.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
end
