function out1 = BMWrapArm_compiled_x_ddot(in1,in2,in3,in4)
%BMWrapArm_compiled_x_ddot
%    OUT1 = BMWrapArm_compiled_x_ddot(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q2 = in1(2,:);
q3 = in1(3,:);
q_d1 = in2(1,:);
q_d2 = in2(2,:);
q_d3 = in2(3,:);
q_dd1 = in3(1,:);
q_dd2 = in3(2,:);
q_dd3 = in3(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t14 = q_d3.*1.466e-1;
t6 = q_d2.*t3;
t7 = q_d1.*t4;
t8 = q_d2.*t5;
t9 = q_d1.*t2.*t3;
t11 = q_d1.*t2.*t5;
t10 = q_d3+t7;
t12 = -t11;
t13 = t8+t9;
t16 = t7.*1.466e-1;
t17 = t8.*1.466e-1;
t18 = t9.*1.466e-1;
t15 = t6+t12;
t19 = t14+t16;
t20 = t17+t18;
mt1 = [q_dd3.*(-1.466e-1)-q_dd1.*t4.*1.466e-1+t15.*t20-q_d2.*(t3.*t13.*1.466e-1-t5.*t15.*1.466e-1)+q_d1.*(q_d2.*t2.*(-1.466e-1)+t2.*t3.*t15.*1.466e-1+t2.*t5.*t13.*1.466e-1);-t10.*t19-t13.*t20];
mt2 = [-q_d1.*(t4.*t6.*1.466e-1-t4.*t15.*1.466e-1+q_d3.*t2.*t5.*1.466e-1-t2.*t5.*t10.*1.466e-1)+q_dd2.*t5.*1.466e-1+t15.*t19-q_d2.*(t3.*t10.*1.466e-1-t3.*t14)+q_d3.*(t6.*1.466e-1-t11.*1.466e-1)+q_dd1.*t2.*t3.*1.466e-1;-q_d1.*(t4.*t6-t4.*t15+q_d3.*t2.*t5-t2.*t5.*t10)+q_d3.*t15+q_dd2.*t5+q_d2.*(q_d3.*t3-t3.*t10)+q_dd1.*t2.*t3];
mt3 = [q_d1.*(t4.*t8-t4.*t13-q_d3.*t2.*t3+t2.*t3.*t10)-q_d3.*t13+q_dd2.*t3-q_d2.*(q_d3.*t5-t5.*t10)-q_dd1.*t2.*t5;q_dd3+q_dd1.*t4+q_d2.*(t3.*t13-t5.*t15)-q_d1.*(-q_d2.*t2+t2.*t3.*t15+t2.*t5.*t13)];
out1 = [mt1;mt2;mt3];
end
