function out1 = BMWrapArm_compiled_S(in1,in2,in3,in4)
%BMWrapArm_compiled_S
%    OUT1 = BMWrapArm_compiled_S(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:05

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q3);
out1 = reshape([0.0,0.0,0.0,t2.*t3,-t2.*t4,sin(q2),0.0,0.0,0.0,t4,t3,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,3]);
end
