function out1 = BMWrapArm_compiled_R_0ks(in1,in2,in3,in4)
%BMWrapArm_compiled_R_0ks
%    OUT1 = BMWrapArm_compiled_R_0ks(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
out1 = reshape([t3.*t4,t2.*t7+t4.*t5.*t6,t5.*t7-t2.*t4.*t6,-t3.*t7,t2.*t4-t5.*t6.*t7,t4.*t5+t2.*t6.*t7,t6,-t3.*t5,t2.*t3],[3,3]);
end
