function out1 = BMWrapArm_compiled_r_OPs(in1,in2,in3,in4)
%BMWrapArm_compiled_r_OPs
%    OUT1 = BMWrapArm_compiled_r_OPs(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

out1 = [0.0;0.0;0.0];
end
