function out1 = BMWrapArm_compiled_G_b(in1,in2,in3,in4)
%BMWrapArm_compiled_G_b
%    OUT1 = BMWrapArm_compiled_G_b(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q3);
t4 = sin(q1);
t5 = sin(q2);
t6 = sin(q3);
out1 = [t4.*t6.*(-9.81e+2./1.0e+2)+t2.*t3.*t5.*(9.81e+2./1.0e+2);t3.*t4.*(-9.81e+2./1.0e+2)-t2.*t5.*t6.*(9.81e+2./1.0e+2);t2.*cos(q2).*(-9.81e+2./1.0e+2);0.0;0.0;0.0];
end
