function out1 = BMWrapArm_compiled_x_dot(in1,in2,in3,in4)
%BMWrapArm_compiled_x_dot
%    OUT1 = BMWrapArm_compiled_x_dot(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Oct-2024 16:27:06

q2 = in1(2,:);
q3 = in1(3,:);
q_d1 = in2(1,:);
q_d2 = in2(2,:);
q_d3 = in2(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
out1 = [q_d3.*(-1.466e-1)-q_d1.*t4.*1.466e-1;0.0;q_d2.*t5.*1.466e-1+q_d1.*t2.*t3.*1.466e-1;q_d2.*t5+q_d1.*t2.*t3;q_d2.*t3-q_d1.*t2.*t5;q_d3+q_d1.*t4];
end
